version: "3.8"
services:
  workspace: 
    build: 
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do:; done"
    volumes:
      - ..:/workspace:cached
    tty: true
    runtime: nvidia
